version: '3.4'

services:
  app:
    image: registry.ql6625.fr/ipapk-server:2
    build:
      context: ../../../../..
      dockerfile: ./go/src/github.com/linktohack/ipapk-server/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./.data:/ipapk/.data
      - ./db.sqlite3:/ipapk/db.sqlite3
      - ./public:/ipapk/public
    environment:
      - VIRTUAL_HOST=apps.docker
      - VIRTUAL_PORT=8080
